/*
 * Generated by Bluespec Compiler, version 2023.01-6-g034050db (build 034050db)
 * 
 * On Fri Apr 28 15:25:38 -03 2023
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTb.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTb::MODEL_mkTb()
{
  mkTb_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTb()
{
  MODEL_mkTb *model = new MODEL_mkTb();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTb &INST_top = *((MOD_mkTb *)(instance_ptr));
	 tUInt8 DEF_INST_top_INST_fir_DEF_n_7_SLE_0___d38;
	 tUInt8 DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7_ETC___d43;
	 tUInt8 DEF_INST_top_INST_fir_DEF_n_7_SLT_42___d234;
	 tUInt8 DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7_ETC___d238;
	 tUInt8 DEF_INST_top_INST_fir_DEF_conv_abort_whas_AND_conv_abort_wget_OR_conv_st_ETC___d270;
	 tUInt8 DEF_INST_top_INST_fir_DEF_conv_abort_whas_AND_conv_abort_wget___d6;
	 tUInt8 DEF_INST_top_INST_fir_DEF_NOT_conv_start_wire_whas_OR_NOT_conv_start_wir_ETC___d11;
	 tUInt8 DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7___d28;
	 tUInt8 DEF_INST_top_INST_fir_DEF_conv_abort_whas_AND_conv_abort_wget_OR_conv_st_ETC___d35;
	 tUInt8 DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read__1_EQ_11___d34;
	 tUInt8 DEF_INST_top_INST_fir_DEF_newSample_i_notEmpty____d225;
	 tUInt8 DEF_INST_top_INST_fir_DEF_conv_start_reg__h37765;
	 tUInt8 DEF_INST_top_INST_fir_DEF_conv_start_wire_wget____d9;
	 tUInt8 DEF_INST_top_INST_fir_DEF_conv_start_wire_whas____d7;
	 tUInt8 DEF_INST_top_INST_fir_DEF_conv_start_reg_1__h28332;
	 tUInt8 DEF_INST_top_INST_fir_DEF_conv_abort_wget____d5;
	 tUInt8 DEF_INST_top_INST_fir_DEF_conv_abort_whas____d4;
	 tUInt8 DEF_INST_top_INST_fir_DEF_conv_state_fired__h28334;
	 tUInt8 DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read____d31;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_start_reg__dreg_update;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_start_reg__dreg_update;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_state_handle_abort;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_state_handle_abort;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_state_fired__dreg_update;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_state_fired__dreg_update;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_state_every;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_state_every;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_restart;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_restart;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_init_l25c9;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l25c38;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_update_l25c9;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l29c16;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l30c18;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_init_l31c9;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l32c16;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l33c16;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_update_l31c9;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l35c12;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l36c13;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_idle_l24c20;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_idle_l24c20;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_fsm_start;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_fsm_start;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_init;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_init;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_10;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_10;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_11;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_11;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_12;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_12;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_13;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_13;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_14;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_14;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_5;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_5;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_6;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_6;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_7;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_7;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_8;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_8;
	 tUInt8 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_9;
	 tUInt8 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_9;
	 tUInt8 DEF_INST_top_DEF_loop_2_SLT_43___d33;
	 tUInt8 DEF_INST_top_DEF_NOT_first_6___d47;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7_8_AND_sta_ETC___d40;
	 tUInt8 DEF_INST_top_DEF_NOT_loop_2_SLT_43_3___d75;
	 tUInt8 DEF_INST_top_DEF_loop_2_SLT_43_3_AND_abort_whas_AND_abort_wget__ETC___d92;
	 tUInt8 DEF_INST_top_DEF_loop_2_SLT_43_3_AND_abort_whas_AND_abort_wget__ETC___d96;
	 tUInt8 DEF_INST_top_DEF_abort_whas_AND_abort_wget___d6;
	 tUInt8 DEF_INST_top_DEF_abort_whas_AND_abort_wget_OR_state_mkFSMstate__ETC___d37;
	 tUInt8 DEF_INST_top_DEF_start_wire_whas_AND_start_wire_wget___d30;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7___d28;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7_8_OR_star_ETC___d31;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__5_EQ_1___d48;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__5_EQ_2___d52;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__5_EQ_6___d39;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__5_EQ_8___d80;
	 tUInt8 DEF_INST_top_DEF_fir_RDY_add_sample____d45;
	 tUInt8 DEF_INST_top_DEF_first__h7113;
	 tUInt8 DEF_INST_top_DEF_abort_wget____d5;
	 tUInt8 DEF_INST_top_DEF_abort_whas____d4;
	 tUInt8 DEF_INST_top_DEF_start_reg__h23483;
	 tUInt8 DEF_INST_top_DEF_running__h23569;
	 tUInt8 DEF_INST_top_DEF_start_wire_wget____d9;
	 tUInt8 DEF_INST_top_DEF_start_wire_whas____d7;
	 tUInt8 DEF_INST_top_DEF_start_reg_1__h21094;
	 tUInt8 DEF_INST_top_DEF_state_fired__h21096;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read____d35;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_every;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_every;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_restart;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_restart;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l18c18;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l20c16;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l23c20;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l24c23;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l26c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l30c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_idle_l17c9;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_idle_l17c9;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_idle_l17c9_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_idle_l17c9_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_auto_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_auto_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_5;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_5;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_6;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_6;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_7;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_7;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_8;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_8;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_9;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_9;
	 DEF_INST_top_DEF_state_mkFSMstate_read____d35 = INST_top.INST_state_mkFSMstate.METH_read();
	 DEF_INST_top_DEF_abort_whas____d4 = INST_top.INST_abort.METH_whas();
	 DEF_INST_top_DEF_abort_wget____d5 = INST_top.INST_abort.METH_wget();
	 DEF_INST_top_DEF_first__h7113 = INST_top.INST_first.METH_read();
	 DEF_INST_top_DEF_fir_RDY_add_sample____d45 = INST_top.INST_fir.METH_RDY_add_sample();
	 DEF_INST_top_DEF_state_mkFSMstate_read__5_EQ_1___d48 = DEF_INST_top_DEF_state_mkFSMstate_read____d35 == (tUInt8)1u;
	 DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7___d28 = !DEF_INST_top_DEF_abort_whas____d4 || !DEF_INST_top_DEF_abort_wget____d5;
	 DEF_INST_top_DEF_NOT_first_6___d47 = !DEF_INST_top_DEF_first__h7113;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l20c16 = DEF_INST_top_DEF_fir_RDY_add_sample____d45 && (DEF_INST_top_DEF_NOT_first_6___d47 && (DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7___d28 && DEF_INST_top_DEF_state_mkFSMstate_read__5_EQ_1___d48));
	 INST_top.DEF_WILL_FIRE_RL_action_l20c16 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l20c16;
	 DEF_INST_top_DEF_state_mkFSMstate_read__5_EQ_2___d52 = DEF_INST_top_DEF_state_mkFSMstate_read____d35 == (tUInt8)2u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l23c20 = DEF_INST_top_DEF_fir_RDY_add_sample____d45 && (DEF_INST_top_DEF_first__h7113 && (DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7___d28 && (DEF_INST_top_DEF_state_mkFSMstate_read__5_EQ_1___d48 || DEF_INST_top_DEF_state_mkFSMstate_read__5_EQ_2___d52)));
	 INST_top.DEF_WILL_FIRE_RL_action_l23c20 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l23c20;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l26c13 = INST_top.INST_fir.METH_RDY_get_value() && (DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7___d28 && DEF_INST_top_DEF_state_mkFSMstate_read____d35 == (tUInt8)4u);
	 INST_top.DEF_WILL_FIRE_RL_action_l26c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l26c13;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l30c13 = DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7___d28 && DEF_INST_top_DEF_state_mkFSMstate_read____d35 == (tUInt8)5u;
	 INST_top.DEF_WILL_FIRE_RL_action_l30c13 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l30c13;
	 INST_top.DEF_b__h6880 = INST_top.INST_loop.METH_read();
	 DEF_INST_top_DEF_state_fired__h21096 = INST_top.INST_state_fired.METH_read();
	 DEF_INST_top_DEF_start_reg_1__h21094 = INST_top.INST_start_reg_1.METH_read();
	 DEF_INST_top_DEF_running__h23569 = INST_top.INST_running.METH_read();
	 DEF_INST_top_DEF_start_reg__h23483 = INST_top.INST_start_reg.METH_read();
	 DEF_INST_top_DEF_state_mkFSMstate_read__5_EQ_8___d80 = DEF_INST_top_DEF_state_mkFSMstate_read____d35 == (tUInt8)8u;
	 DEF_INST_top_DEF_state_mkFSMstate_read__5_EQ_6___d39 = DEF_INST_top_DEF_state_mkFSMstate_read____d35 == (tUInt8)6u;
	 DEF_INST_top_DEF_abort_whas_AND_abort_wget___d6 = DEF_INST_top_DEF_abort_whas____d4 && DEF_INST_top_DEF_abort_wget____d5;
	 DEF_INST_top_DEF_abort_whas_AND_abort_wget_OR_state_mkFSMstate__ETC___d37 = DEF_INST_top_DEF_abort_whas_AND_abort_wget___d6 || DEF_INST_top_DEF_state_mkFSMstate_read____d35 == (tUInt8)0u;
	 DEF_INST_top_DEF_loop_2_SLT_43___d33 = primSLT8(1u,
							 8u,
							 (tUInt8)(INST_top.DEF_b__h6880),
							 8u,
							 (tUInt8)43u);
	 DEF_INST_top_DEF_NOT_loop_2_SLT_43_3___d75 = !DEF_INST_top_DEF_loop_2_SLT_43___d33;
	 DEF_INST_top_DEF_loop_2_SLT_43_3_AND_abort_whas_AND_abort_wget__ETC___d92 = (((DEF_INST_top_DEF_loop_2_SLT_43___d33 && DEF_INST_top_DEF_abort_whas_AND_abort_wget_OR_state_mkFSMstate__ETC___d37) || ((DEF_INST_top_DEF_loop_2_SLT_43___d33 && (DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7___d28 && DEF_INST_top_DEF_state_mkFSMstate_read__5_EQ_8___d80)) || (DEF_INST_top_DEF_NOT_loop_2_SLT_43_3___d75 && DEF_INST_top_DEF_abort_whas_AND_abort_wget_OR_state_mkFSMstate__ETC___d37))) || (DEF_INST_top_DEF_NOT_loop_2_SLT_43_3___d75 && (DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7___d28 && (DEF_INST_top_DEF_state_mkFSMstate_read__5_EQ_6___d39 || DEF_INST_top_DEF_state_mkFSMstate_read__5_EQ_8___d80)))) && (!DEF_INST_top_DEF_start_reg_1__h21094 || DEF_INST_top_DEF_state_fired__h21096);
	 DEF_INST_top_DEF_loop_2_SLT_43_3_AND_abort_whas_AND_abort_wget__ETC___d96 = DEF_INST_top_DEF_loop_2_SLT_43_3_AND_abort_whas_AND_abort_wget__ETC___d92 && !DEF_INST_top_DEF_start_reg__h23483;
	 DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish = DEF_INST_top_DEF_running__h23569 && DEF_INST_top_DEF_loop_2_SLT_43_3_AND_abort_whas_AND_abort_wget__ETC___d96;
	 DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish = DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish;
	 DEF_INST_top_DEF_CAN_FIRE_RL_auto_start = DEF_INST_top_DEF_loop_2_SLT_43_3_AND_abort_whas_AND_abort_wget__ETC___d96 && !DEF_INST_top_DEF_running__h23569;
	 DEF_INST_top_DEF_WILL_FIRE_RL_auto_start = DEF_INST_top_DEF_CAN_FIRE_RL_auto_start;
	 DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start = DEF_INST_top_DEF_loop_2_SLT_43_3_AND_abort_whas_AND_abort_wget__ETC___d92 && DEF_INST_top_DEF_start_reg__h23483;
	 DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start = DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start;
	 DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7_8_AND_sta_ETC___d40 = DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7___d28 && DEF_INST_top_DEF_state_mkFSMstate_read__5_EQ_6___d39;
	 DEF_INST_top_DEF_CAN_FIRE_RL_idle_l17c9_1 = DEF_INST_top_DEF_NOT_loop_2_SLT_43_3___d75 && DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7_8_AND_sta_ETC___d40;
	 DEF_INST_top_DEF_WILL_FIRE_RL_idle_l17c9_1 = DEF_INST_top_DEF_CAN_FIRE_RL_idle_l17c9_1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_restart = (DEF_INST_top_DEF_start_reg_1__h21094 && !DEF_INST_top_DEF_state_fired__h21096) && DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7___d28;
	 DEF_INST_top_DEF_WILL_FIRE_RL_restart = DEF_INST_top_DEF_CAN_FIRE_RL_restart;
	 DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update = DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_every = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_every = DEF_INST_top_DEF_CAN_FIRE_RL_state_every;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update = DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_8 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_8 = DEF_INST_top_DEF_CAN_FIRE___me_check_8;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_5 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_5 = DEF_INST_top_DEF_CAN_FIRE___me_check_5;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_6 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_6 = DEF_INST_top_DEF_CAN_FIRE___me_check_6;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_7 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_7 = DEF_INST_top_DEF_CAN_FIRE___me_check_7;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_9 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_9 = DEF_INST_top_DEF_CAN_FIRE___me_check_9;
	 DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read____d31 = INST_top.INST_fir.INST_conv_state_mkFSMstate.METH_read();
	 DEF_INST_top_INST_fir_DEF_conv_abort_whas____d4 = INST_top.INST_fir.INST_conv_abort.METH_whas();
	 DEF_INST_top_INST_fir_DEF_conv_abort_wget____d5 = INST_top.INST_fir.INST_conv_abort.METH_wget();
	 DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7___d28 = !DEF_INST_top_INST_fir_DEF_conv_abort_whas____d4 || !DEF_INST_top_INST_fir_DEF_conv_abort_wget____d5;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_init_l31c9 = DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7___d28 && DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read____d31 == (tUInt8)5u;
	 INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_f_init_l31c9 = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_init_l31c9;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_update_l31c9 = DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7___d28 && DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read____d31 == (tUInt8)8u;
	 INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_f_update_l31c9 = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_update_l31c9;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_update_l25c9 = DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7___d28 && DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read____d31 == (tUInt8)2u;
	 INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_f_update_l25c9 = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_update_l25c9;
	 INST_top.INST_fir.DEF_x__h36308 = INST_top.INST_fir.INST_n.METH_read();
	 DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7_ETC___d43 = DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7___d28 && (DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read____d31 == (tUInt8)1u || DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read____d31 == (tUInt8)3u);
	 DEF_INST_top_INST_fir_DEF_n_7_SLE_0___d38 = primSLE8(1u,
							      7u,
							      (tUInt8)(INST_top.INST_fir.DEF_x__h36308),
							      7u,
							      (tUInt8)0u);
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l25c38 = !DEF_INST_top_INST_fir_DEF_n_7_SLE_0___d38 && DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7_ETC___d43;
	 INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_l25c38 = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l25c38;
	 DEF_INST_top_INST_fir_DEF_newSample_i_notEmpty____d225 = INST_top.INST_fir.INST_newSample.METH_i_notEmpty();
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l29c16 = DEF_INST_top_INST_fir_DEF_newSample_i_notEmpty____d225 && (DEF_INST_top_INST_fir_DEF_n_7_SLE_0___d38 && DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7_ETC___d43);
	 INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_l29c16 = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l29c16;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l30c18 = DEF_INST_top_INST_fir_DEF_newSample_i_notEmpty____d225 && (DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7___d28 && DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read____d31 == (tUInt8)4u);
	 INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_l30c18 = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l30c18;
	 DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7_ETC___d238 = DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7___d28 && (DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read____d31 == (tUInt8)6u || DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read____d31 == (tUInt8)9u);
	 DEF_INST_top_INST_fir_DEF_n_7_SLT_42___d234 = primSLT8(1u,
								7u,
								(tUInt8)(INST_top.INST_fir.DEF_x__h36308),
								7u,
								(tUInt8)42u);
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l32c16 = DEF_INST_top_INST_fir_DEF_n_7_SLT_42___d234 && DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7_ETC___d238;
	 INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_l32c16 = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l32c16;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l33c16 = DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7___d28 && DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read____d31 == (tUInt8)7u;
	 INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_l33c16 = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l33c16;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l36c13 = DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7___d28 && DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read____d31 == (tUInt8)10u;
	 INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_l36c13 = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l36c13;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l35c12 = INST_top.INST_fir.INST_acc.METH_i_notFull() && (!DEF_INST_top_INST_fir_DEF_n_7_SLT_42___d234 && DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7_ETC___d238);
	 INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_l35c12 = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l35c12;
	 DEF_INST_top_INST_fir_DEF_conv_state_fired__h28334 = INST_top.INST_fir.INST_conv_state_fired.METH_read();
	 DEF_INST_top_INST_fir_DEF_conv_start_reg_1__h28332 = INST_top.INST_fir.INST_conv_start_reg_1.METH_read();
	 DEF_INST_top_INST_fir_DEF_conv_start_reg__h37765 = INST_top.INST_fir.INST_conv_start_reg.METH_read();
	 DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read__1_EQ_11___d34 = DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read____d31 == (tUInt8)11u;
	 DEF_INST_top_INST_fir_DEF_conv_abort_whas_AND_conv_abort_wget___d6 = DEF_INST_top_INST_fir_DEF_conv_abort_whas____d4 && DEF_INST_top_INST_fir_DEF_conv_abort_wget____d5;
	 DEF_INST_top_INST_fir_DEF_conv_abort_whas_AND_conv_abort_wget_OR_conv_st_ETC___d35 = (DEF_INST_top_INST_fir_DEF_conv_abort_whas_AND_conv_abort_wget___d6 || DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read____d31 == (tUInt8)0u) || DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read__1_EQ_11___d34;
	 DEF_INST_top_INST_fir_DEF_conv_abort_whas_AND_conv_abort_wget_OR_conv_st_ETC___d270 = DEF_INST_top_INST_fir_DEF_conv_abort_whas_AND_conv_abort_wget_OR_conv_st_ETC___d35 && (!DEF_INST_top_INST_fir_DEF_conv_start_reg_1__h28332 || DEF_INST_top_INST_fir_DEF_conv_state_fired__h28334);
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_fsm_start = DEF_INST_top_INST_fir_DEF_conv_abort_whas_AND_conv_abort_wget_OR_conv_st_ETC___d270 && DEF_INST_top_INST_fir_DEF_conv_start_reg__h37765;
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_fsm_start = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_fsm_start;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_restart = (DEF_INST_top_INST_fir_DEF_conv_start_reg_1__h28332 && !DEF_INST_top_INST_fir_DEF_conv_state_fired__h28334) && DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7___d28;
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_restart = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_restart;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_start_reg__dreg_update = (tUInt8)1u;
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_start_reg__dreg_update = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_start_reg__dreg_update;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_state_fired__dreg_update = (tUInt8)1u;
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_state_fired__dreg_update = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_state_fired__dreg_update;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_state_every = (tUInt8)1u;
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_state_every = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_state_every;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_init = DEF_INST_top_INST_fir_DEF_conv_abort_whas_AND_conv_abort_wget_OR_conv_st_ETC___d270 && !DEF_INST_top_INST_fir_DEF_conv_start_reg__h37765;
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_init = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_init;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_10 = (tUInt8)1u;
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_10 = DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_10;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_14 = (tUInt8)1u;
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_14 = DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_14;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_11 = (tUInt8)1u;
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_11 = DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_11;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_12 = (tUInt8)1u;
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_12 = DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_12;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_13 = (tUInt8)1u;
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_13 = DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_13;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_5 = (tUInt8)1u;
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_5 = DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_5;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_6 = (tUInt8)1u;
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_6 = DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_6;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_7 = (tUInt8)1u;
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_7 = DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_7;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_9 = (tUInt8)1u;
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_9 = DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_9;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_8 = (tUInt8)1u;
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_8 = DEF_INST_top_INST_fir_DEF_CAN_FIRE___me_check_8;
	 if (INST_top.DEF_WILL_FIRE_RL_action_l20c16)
	   INST_top.RL_action_l20c16();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l23c20)
	   INST_top.RL_action_l23c20();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l26c13)
	   INST_top.RL_action_l26c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l30c13)
	   INST_top.RL_action_l30c13();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish)
	   INST_top.RL_auto_finish();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_auto_start)
	   INST_top.RL_auto_start();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start)
	   INST_top.RL_fsm_start();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_restart)
	   INST_top.RL_restart();
	 DEF_INST_top_DEF_start_wire_whas____d7 = INST_top.INST_start_wire.METH_whas();
	 DEF_INST_top_DEF_start_wire_wget____d9 = INST_top.INST_start_wire.METH_wget();
	 DEF_INST_top_DEF_start_wire_whas_AND_start_wire_wget___d30 = DEF_INST_top_DEF_start_wire_whas____d7 && DEF_INST_top_DEF_start_wire_wget____d9;
	 DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7_8_OR_star_ETC___d31 = DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7___d28 || DEF_INST_top_DEF_start_wire_whas_AND_start_wire_wget___d30;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l18c18 = (DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7_8_OR_star_ETC___d31 && (((DEF_INST_top_DEF_loop_2_SLT_43___d33 && DEF_INST_top_DEF_start_wire_whas_AND_start_wire_wget___d30) && DEF_INST_top_DEF_abort_whas_AND_abort_wget_OR_state_mkFSMstate__ETC___d37) || (DEF_INST_top_DEF_loop_2_SLT_43___d33 && DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7_8_AND_sta_ETC___d40))) && !((DEF_INST_top_DEF_CAN_FIRE_RL_action_l30c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l26c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l23c20 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l20c16));
	 INST_top.DEF_WILL_FIRE_RL_action_l18c18 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l18c18;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l24c23 = (DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7_8_OR_star_ETC___d31 && ((DEF_INST_top_DEF_NOT_first_6___d47 && (DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7___d28 && DEF_INST_top_DEF_state_mkFSMstate_read__5_EQ_2___d52)) || (DEF_INST_top_DEF_NOT_abort_whas_6_OR_NOT_abort_wget_7___d28 && DEF_INST_top_DEF_state_mkFSMstate_read____d35 == (tUInt8)3u))) && !(((DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish || DEF_INST_top_DEF_CAN_FIRE_RL_auto_start) || (DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start || DEF_INST_top_DEF_CAN_FIRE_RL_action_l30c13)) || ((DEF_INST_top_DEF_CAN_FIRE_RL_action_l26c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l23c20) || DEF_INST_top_DEF_CAN_FIRE_RL_action_l20c16));
	 INST_top.DEF_WILL_FIRE_RL_action_l24c23 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l24c23;
	 DEF_INST_top_DEF_CAN_FIRE_RL_idle_l17c9 = ((DEF_INST_top_DEF_NOT_loop_2_SLT_43_3___d75 && DEF_INST_top_DEF_start_wire_whas_AND_start_wire_wget___d30) && DEF_INST_top_DEF_abort_whas_AND_abort_wget_OR_state_mkFSMstate__ETC___d37) && !((DEF_INST_top_DEF_CAN_FIRE_RL_action_l30c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l26c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l23c20 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l20c16));
	 DEF_INST_top_DEF_WILL_FIRE_RL_idle_l17c9 = DEF_INST_top_DEF_CAN_FIRE_RL_idle_l17c9;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort = (DEF_INST_top_DEF_abort_whas_AND_abort_wget___d6 && (!DEF_INST_top_DEF_start_wire_whas____d7 || !DEF_INST_top_DEF_start_wire_wget____d9)) && !(((DEF_INST_top_DEF_CAN_FIRE_RL_action_l30c13 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l26c13) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l23c20 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l20c16)) || DEF_INST_top_DEF_CAN_FIRE_RL_restart);
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort = DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort;
	 if (INST_top.DEF_WILL_FIRE_RL_action_l18c18)
	   INST_top.RL_action_l18c18();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l24c23)
	   INST_top.RL_action_l24c23();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort)
	   INST_top.RL_state_handle_abort();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_5)
	   INST_top.__me_check_5();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update)
	   INST_top.RL_start_reg__dreg_update();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_6)
	   INST_top.__me_check_6();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_7)
	   INST_top.__me_check_7();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_8)
	   INST_top.__me_check_8();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_idle_l17c9)
	   INST_top.RL_idle_l17c9();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_9)
	   INST_top.__me_check_9();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_idle_l17c9_1)
	   INST_top.RL_idle_l17c9_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_every)
	   INST_top.RL_state_every();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update)
	   INST_top.RL_state_fired__dreg_update();
	 if (INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_f_init_l31c9)
	   INST_top.INST_fir.RL_conv_action_f_init_l31c9();
	 if (INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_f_update_l31c9)
	   INST_top.INST_fir.RL_conv_action_f_update_l31c9();
	 if (INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_f_update_l25c9)
	   INST_top.INST_fir.RL_conv_action_f_update_l25c9();
	 if (INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_l25c38)
	   INST_top.INST_fir.RL_conv_action_l25c38();
	 if (INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_l29c16)
	   INST_top.INST_fir.RL_conv_action_l29c16();
	 if (INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_l30c18)
	   INST_top.INST_fir.RL_conv_action_l30c18();
	 if (INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_l32c16)
	   INST_top.INST_fir.RL_conv_action_l32c16();
	 if (INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_l33c16)
	   INST_top.INST_fir.RL_conv_action_l33c16();
	 if (INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_l36c13)
	   INST_top.INST_fir.RL_conv_action_l36c13();
	 if (INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_l35c12)
	   INST_top.INST_fir.RL_conv_action_l35c12();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_restart)
	   INST_top.INST_fir.RL_conv_restart();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_init)
	   INST_top.INST_fir.RL_init();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_6)
	   INST_top.INST_fir.__me_check_6();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_7)
	   INST_top.INST_fir.__me_check_7();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_8)
	   INST_top.INST_fir.__me_check_8();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_9)
	   INST_top.INST_fir.__me_check_9();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_10)
	   INST_top.INST_fir.__me_check_10();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_11)
	   INST_top.INST_fir.__me_check_11();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_12)
	   INST_top.INST_fir.__me_check_12();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_13)
	   INST_top.INST_fir.__me_check_13();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_14)
	   INST_top.INST_fir.__me_check_14();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_fsm_start)
	   INST_top.INST_fir.RL_conv_fsm_start();
	 DEF_INST_top_INST_fir_DEF_conv_start_wire_whas____d7 = INST_top.INST_fir.INST_conv_start_wire.METH_whas();
	 DEF_INST_top_INST_fir_DEF_conv_start_wire_wget____d9 = INST_top.INST_fir.INST_conv_start_wire.METH_wget();
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_init_l25c9 = ((DEF_INST_top_INST_fir_DEF_conv_start_wire_whas____d7 && DEF_INST_top_INST_fir_DEF_conv_start_wire_wget____d9) && DEF_INST_top_INST_fir_DEF_conv_abort_whas_AND_conv_abort_wget_OR_conv_st_ETC___d35) && !((((DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l36c13 || DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l35c12) || (DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_update_l31c9 || DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l33c16)) || ((DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l32c16 || DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_init_l31c9) || (DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l30c18 || DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l29c16))) || (DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_update_l25c9 || DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l25c38));
	 INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_f_init_l25c9 = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_init_l25c9;
	 DEF_INST_top_INST_fir_DEF_NOT_conv_start_wire_whas_OR_NOT_conv_start_wir_ETC___d11 = !DEF_INST_top_INST_fir_DEF_conv_start_wire_whas____d7 || !DEF_INST_top_INST_fir_DEF_conv_start_wire_wget____d9;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_idle_l24c20 = (DEF_INST_top_INST_fir_DEF_NOT_conv_start_wire_whas_OR_NOT_conv_start_wir_ETC___d11 && (DEF_INST_top_INST_fir_DEF_NOT_conv_abort_whas_6_OR_NOT_conv_abort_wget_7___d28 && DEF_INST_top_INST_fir_DEF_conv_state_mkFSMstate_read__1_EQ_11___d34)) && !((((DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l36c13 || DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l35c12) || (DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_update_l31c9 || DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l33c16)) || ((DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l32c16 || DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_init_l31c9) || (DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l30c18 || DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l29c16))) || (DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_update_l25c9 || DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l25c38));
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_idle_l24c20 = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_idle_l24c20;
	 DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_state_handle_abort = (DEF_INST_top_INST_fir_DEF_conv_abort_whas_AND_conv_abort_wget___d6 && DEF_INST_top_INST_fir_DEF_NOT_conv_start_wire_whas_OR_NOT_conv_start_wir_ETC___d11) && !((((DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l36c13 || DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l35c12) || (DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_update_l31c9 || DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l33c16)) || ((DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l32c16 || DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_init_l31c9) || (DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l30c18 || DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l29c16))) || ((DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_f_update_l25c9 || DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_action_l25c38) || DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_restart));
	 DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_state_handle_abort = DEF_INST_top_INST_fir_DEF_CAN_FIRE_RL_conv_state_handle_abort;
	 if (INST_top.INST_fir.DEF_WILL_FIRE_RL_conv_action_f_init_l25c9)
	   INST_top.INST_fir.RL_conv_action_f_init_l25c9();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_start_reg__dreg_update)
	   INST_top.INST_fir.RL_conv_start_reg__dreg_update();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_state_handle_abort)
	   INST_top.INST_fir.RL_conv_state_handle_abort();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE___me_check_5)
	   INST_top.INST_fir.__me_check_5();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_idle_l24c20)
	   INST_top.INST_fir.RL_conv_idle_l24c20();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_state_every)
	   INST_top.INST_fir.RL_conv_state_every();
	 if (DEF_INST_top_INST_fir_DEF_WILL_FIRE_RL_conv_state_fired__dreg_update)
	   INST_top.INST_fir.RL_conv_state_fired__dreg_update();
	 INST_top.INST_state_fired_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_state_overlap_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_state_set_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_abort.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_start_reg_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_start_wire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fir.INST_conv_state_fired_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fir.INST_conv_state_overlap_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fir.INST_conv_state_set_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fir.INST_conv_abort.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fir.INST_conv_start_reg_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_fir.INST_conv_start_wire.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_fir.INST_samples_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_16.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_17.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_18.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_19.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_20.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_21.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_22.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_23.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_24.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_25.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_26.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_27.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_28.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_29.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_30.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_31.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_32.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_33.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_34.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_35.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_36.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_37.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_38.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_39.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_40.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_41.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_samples_42.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_acc.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fir.INST_newSample.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_fir.INST_sum.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_n.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_conv_start_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_conv_start_reg_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_conv_state_mkFSMstate.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_conv_state_fired.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fir.INST_conv_state_can_overlap.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_first.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_loop.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_result.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_start_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_start_reg_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_mkFSMstate.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_fired.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_can_overlap.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_running.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTb::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTb_instance = new MOD_mkTb(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTb_instance->INST_fir.INST_acc.set_clk_0)("CLK");
  (mkTb_instance->INST_fir.INST_newSample.set_clk_0)("CLK");
  (mkTb_instance->INST_fir.INST_conv_start_wire.set_clk_0)("CLK");
  (mkTb_instance->INST_fir.INST_conv_start_reg_2.set_clk_0)("CLK");
  (mkTb_instance->INST_fir.INST_conv_abort.set_clk_0)("CLK");
  (mkTb_instance->INST_fir.INST_conv_state_set_pw.set_clk_0)("CLK");
  (mkTb_instance->INST_fir.INST_conv_state_overlap_pw.set_clk_0)("CLK");
  (mkTb_instance->INST_fir.INST_conv_state_fired_1.set_clk_0)("CLK");
  (mkTb_instance->INST_fir.set_clk_0)("CLK");
  (mkTb_instance->INST_start_wire.set_clk_0)("CLK");
  (mkTb_instance->INST_start_reg_2.set_clk_0)("CLK");
  (mkTb_instance->INST_abort.set_clk_0)("CLK");
  (mkTb_instance->INST_state_set_pw.set_clk_0)("CLK");
  (mkTb_instance->INST_state_overlap_pw.set_clk_0)("CLK");
  (mkTb_instance->INST_state_fired_1.set_clk_0)("CLK");
  (mkTb_instance->set_clk_0)("CLK");
}
void MODEL_mkTb::destroy_model()
{
  delete mkTb_instance;
  mkTb_instance = NULL;
}
void MODEL_mkTb::reset_model(bool asserted)
{
  (mkTb_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTb::get_instance()
{
  return mkTb_instance;
}

/* Fill in version numbers */
void MODEL_mkTb::get_version(char const **name, char const **build)
{
  *name = "2023.01-6-g034050db";
  *build = "034050db";
}

/* Get the model creation time */
time_t MODEL_mkTb::get_creation_time()
{
  
  /* Fri Apr 28 18:25:38 UTC 2023 */
  return 1682706338llu;
}

/* State dumping function */
void MODEL_mkTb::dump_state()
{
  (mkTb_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTb & mkTb_backing(tSimStateHdl simHdl)
{
  static MOD_mkTb *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTb(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTb::dump_VCD_defs()
{
  (mkTb_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTb::dump_VCD(tVCDDumpType dt)
{
  (mkTb_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTb_backing(sim_hdl));
}
