/*
 * Generated by Bluespec Compiler, version 2023.01-6-g034050db (build 034050db)
 * 
 * On Fri Apr 14 15:31:52 -03 2023
 * 
 */

/* Generation options: */
#ifndef __mkCBusExample_h__
#define __mkCBusExample_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkCounterSynth.h"


/* Class declaration for the mkCBusExample module */
class MOD_mkCBusExample : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkCounterSynth INST_the_counter;
 
 /* Constructor */
 public:
  MOD_mkCBusExample(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUInt64 DEF_v__h105;
  tUInt64 DEF_the_counter_cbus_ifc_read_13___d1;
  tUInt32 DEF_x__h247;
  tUInt32 DEF_read_value__h215;
 
 /* Rules */
 public:
  void RL_display_value();
  void RL_init_counter();
  void RL_decrement();
  void RL_done();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkCBusExample &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkCBusExample &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkCBusExample &backing);
};

#endif /* ifndef __mkCBusExample_h__ */
