/*
 * Generated by Bluespec Compiler, version 2023.01-6-g034050db (build 034050db)
 * 
 * On Fri Apr 14 15:31:52 -03 2023
 * 
 */

/* Generation options: */
#ifndef __mkCounterSynth_h__
#define __mkCounterSynth_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkCounterSynth module */
class MOD_mkCounterSynth : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_counter;
 
 /* Constructor */
 public:
  MOD_mkCounterSynth(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUInt8 DEF_x_device_ifc__read__h386;
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  void METH_cbus_ifc_write(tUInt32 ARG_cbus_ifc_write_addr, tUInt32 ARG_cbus_ifc_write_data);
  tUInt8 METH_RDY_cbus_ifc_write();
  tUInt64 METH_cbus_ifc_read(tUInt32 ARG_cbus_ifc_read_addr);
  tUInt8 METH_RDY_cbus_ifc_read();
  tUInt8 METH_device_ifc_isZero();
  tUInt8 METH_RDY_device_ifc_isZero();
  void METH_device_ifc_decrement();
  tUInt8 METH_RDY_device_ifc_decrement();
  void METH_device_ifc_load(tUInt8 ARG_device_ifc_load_newval);
  tUInt8 METH_RDY_device_ifc_load();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkCounterSynth &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkCounterSynth &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkCounterSynth &backing);
};

#endif /* ifndef __mkCounterSynth_h__ */
