//
// Generated by Bluespec Compiler, version 2021.07 (build 4cac6eb)
//
// On Tue Jan 11 16:13:46 -03 2022
//
//
// Ports:
// Name                         I/O  size props
// map                            O    26
// RDY_map                        O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// map_bits                       I     2
//
// Combinational paths from inputs to outputs:
//   map_bits -> map
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkQPSKmapper(CLK,
		    RST_N,

		    map_bits,
		    map,
		    RDY_map);
  input  CLK;
  input  RST_N;

  // value method map
  input  [1 : 0] map_bits;
  output [25 : 0] map;
  output RDY_map;

  // signals for module outputs
  wire [25 : 0] map;
  wire RDY_map;

  // remaining internal signals
  reg [12 : 0] CASE_map_bits_0b0_8191_0b1_1_0b10_8191_0b11_1__ETC__q2,
	       CASE_map_bits_0b0_8191_0b1_8191_0b10_1_0b11_1__ETC__q1;

  // value method map
  assign map =
	     { CASE_map_bits_0b0_8191_0b1_8191_0b10_1_0b11_1__ETC__q1,
	       CASE_map_bits_0b0_8191_0b1_1_0b10_8191_0b11_1__ETC__q2 } ;
  assign RDY_map = 1'd1 ;

  // remaining internal signals
  always@(map_bits)
  begin
    case (map_bits)
      2'b0, 2'b01:
	  CASE_map_bits_0b0_8191_0b1_8191_0b10_1_0b11_1__ETC__q1 = 13'd8191;
      2'b10, 2'b11:
	  CASE_map_bits_0b0_8191_0b1_8191_0b10_1_0b11_1__ETC__q1 = 13'd1;
    endcase
  end
  always@(map_bits)
  begin
    case (map_bits)
      2'b0, 2'b10:
	  CASE_map_bits_0b0_8191_0b1_1_0b10_8191_0b11_1__ETC__q2 = 13'd8191;
      2'b01, 2'b11:
	  CASE_map_bits_0b0_8191_0b1_1_0b10_8191_0b11_1__ETC__q2 = 13'd1;
    endcase
  end
endmodule  // mkQPSKmapper

