//
// Generated by Bluespec Compiler, version 2021.07 (build 4cac6eb)
//
// On Tue Jan 11 16:15:06 -03 2022
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTb(CLK,
	    RST_N);
  input  CLK;
  input  RST_N;

  // ports of submodule mapper
  wire [25 : 0] mapper$map;
  wire [1 : 0] mapper$map_bits;

  // submodule mapper
  mkQPSKmapper mapper(.CLK(CLK),
		      .RST_N(RST_N),
		      .map_bits(mapper$map_bits),
		      .map(mapper$map),
		      .RDY_map());

  // submodule mapper
  assign mapper$map_bits = 2'b0 ;

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    $write("map of 00 is: ");
    $write("<C ");
    $write("%d", $signed(mapper$map[25:13]));
    $write(",");
    $write("%d", $signed(mapper$map[12:0]), ">");
    $write("\n");
    $finish(32'd0);
  end
  // synopsys translate_on
endmodule  // mkTb

